select 'drop table "'||table_name||'" cascade constraints;' from user_tables;

drop table "COUNTRIES" cascade constraints;
drop table "DEPARTMENTS" cascade constraints;
drop table "EMPLOYEES" cascade constraints;
drop table "JOBS" cascade constraints;
drop table "JOB_HISTORY" cascade constraints;
drop table "LOCATIONS" cascade constraints;
drop table "REGIONS" cascade constraints;



CREATE TABLE COUNTRIES AS SELECT COUNTRY_ID ,COUNTRY_NAME, REGION_ID FROM HR.countries;

CREATE TABLE DEPARTMENTS AS SELECT * FROM HR.departments;
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.employees;
CREATE TABLE JOB_GRADES AS SELECT * FROM HR.job_grades;

CREATE TABLE JOB_HISTORY AS SELECT * FROM HR.job_history;
CREATE TABLE JOBS AS SELECT * FROM HR.jobs;
CREATE TABLE LOCATIONS AS SELECT * FROM HR.locations;
CREATE TABLE REGIONS AS SELECT * FROM HR.regions;

ALTER TABLE REGIONS
ADD PRIMARY KEY (REGION_ID);

ALTER TABLE COUNTRIES
ADD PRIMARY KEY (COUNTRY_ID)
ADD FOREIGN KEY (REGION_ID)
REFERENCES REGIONS(REGION_ID) ON DELETE CASCADE;

ALTER TABLE LOCATIONS
ADD PRIMARY KEY (LOCATION_ID)
ADD FOREIGN KEY (COUNTRY_ID)
REFERENCES COUNTRIES(COUNTRY_ID) ON DELETE CASCADE;

ALTER TABLE JOBS
ADD PRIMARY KEY (JOB_ID);

ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPARTMENT_ID)
ADD FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATIONS(LOCATION_ID) ON DELETE CASCADE;

ALTER TABLE EMPLOYEES
ADD PRIMARY KEY (EMPLOYEE_ID)
ADD FOREIGN KEY (JOB_ID)
REFERENCES JOBS(JOB_ID) ON DELETE CASCADE
ADD FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE CASCADE;


ALTER TABLE JOB_HISTORY
ADD PRIMARY KEY (EMPLOYEE_ID, START_DATE)
ADD FOREIGN KEY (JOB_ID)
REFERENCES JOBS(JOB_ID) ON DELETE CASCADE
ADD FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE CASCADE
ADD FOREIGN KEY (EMPLOYEE_ID)
REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE;

ALTER TABLE EMPLOYEES
ADD FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES(EMPLOYEE_ID);


SELECT (last_name||' '||salary) AS wynagrodzenie FROM EMPLOYEES WHERE
(DEPARTMENT_ID=20 OR DEPARTMENT_ID=50) AND (SALARY > 2000 AND SALARY <7000)

SELECT HIRE_DATE, LAST_NAME, &col
FROM EMPLOYEES
WHERE (SUBSTR(HIRE_DATE,1,2)='05' AND MANAGER_ID IS NOT NULL)
ORDER BY &col;


SELECT FIRST_NAME||' '||LAST_NAME as NAME, SALARY, PHONE_NUMBER
FROM EMPLOYEES
WHERE ((REGEXP_LIKE(FIRST_NAME, '&IN') AND (SUBSTR(LAST_NAME,3,1)='c')))
ORDER BY 1 DESC,2 ASC;

SELECT EMPLOYEES.SALARY
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE EMPLOYEES.SALARY>5000;
 
SELECT E.LAST_NAME,D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.JOB_ID
FROM EMPLOYEES E JOIN
    departments D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID JOIN
    LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
WHERE L.CITY ='Toronto';
    
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME ='Jennifer';

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID 
NOT IN (SELECT DEPARTMENT_ID FROM EMPLOYEES);

CREATE TABLE JOB_GRADES AS( SELECT * FROM HR.job_grades);

